#Load Antigen
ANTIGEN_CACHE=false
source ~/antigen.zsh

#Load OMZsh
antigen use oh-my-zsh
antigen theme https://github.com/denysdovhan/spaceship-zsh-theme spaceship

# OMZsh plugins
antigen bundle osx
antigen bundle docker

# Other Plugins
antigen bundle zsh-users/zsh-syntax-highlighting

# Apply Antigen config
antigen apply

#General Shell stuff
alias ll="ls -alht"
alias wq="exit"
alias :wq="exit"
alias nuke="rm -Rf $"
unset GREP_OPTIONS
alias grep="grep --color=auto --exclude-dir=.cvs --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn"

#Fix tab completion weirdness
export LC_ALL=en_US.UTF-8
export TERM=xterm-256color

#Add fuzzy finder support
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
